name: Node.js CI
on:
  push:
    branches: ["WH-KB-Playwright"]
  pull_request:
    branches: ["dev", "WH-KB-Playwright"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm ci --prefix=client
      - run: npm ci --prefix=api
      - run: npm run ci
